"""Adding table

Revision ID: 599ad4ab14d0
Revises: 
Create Date: 2020-04-21 02:30:16.050999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599ad4ab14d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
