"""Initiate Migration

Revision ID: bf5329f66eb6
Revises: 1dd82e280596
Create Date: 2020-04-21 19:39:48.233699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5329f66eb6'
down_revision = '1dd82e280596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.add_column('org_jobs', sa.Column('job_description', sa.String(length=2000), nullable=True))
    op.add_column('org_jobs', sa.Column('job_location', sa.String(length=100), nullable=True))
    op.add_column('org_jobs', sa.Column('job_title', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'org_jobs', ['job_id'])
    op.drop_constraint(None, 'org_jobs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'org_jobs', 'jobs', ['job_id'], ['job_id'])
    op.drop_constraint(None, 'org_jobs', type_='unique')
    op.drop_column('org_jobs', 'job_title')
    op.drop_column('org_jobs', 'job_location')
    op.drop_column('org_jobs', 'job_description')
    op.create_table('jobs',
    sa.Column('job_id', sa.INTEGER(), nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('job_description', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('job_location', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###
